# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: Expose ports only to a local network address
version: '3'
services:
  appliance:
    build:
      context: .
      dockerfile: "Dockerfile_appliance"
    image: "appliance:${VER}"
    privileged: true
    ports:
     - "42101:42101"
     - "42102:42102"
     - "192.168.122.1:443:443"
     - "192.168.122.1:80:80"
    volumes:
     - "/etc/pki/tls/certs:/host_certs"
     - "/proc/1/ns:/var/host_ns:ro"
     - "/var/lib/appliance/nts:/var/lib/appliance/nts"
     - "/run:/run"
     - "/var/run/docker/netns:/var/run/docker/netns"
     - "/sys/class/net:/var/host_net_devices"
     - "/sys/devices:/devices"
     - "/var/lib/appliance/certs:/root/certs"
     - "/var/lib/appliance/configs:/root/configs"
     - "/var/lib/appliance/applications:/var/lib/appliance/applications"
    network_mode: bridge

  edgednssvr:
    container_name: mec-app-edgednssvr
    build:
      context: .
      dockerfile: "Dockerfile_edgednssvr"
    image: "edgednssvr:${VER}"
    cap_add:
     - NET_ADMIN
    volumes:
     - "/var/lib/appliance/edgednssvr:/var/lib/edgedns"
     - "/run:/run"
    environment:
     - http_proxy
     - https_proxy
     - DNS_FWDR=8.8.8.8
     - LOCAL_SYSLOG=192.168.122.1:514
    network_mode: bridge

  nts:
    container_name: nts
    build:
      context: .
      dockerfile: "Dockerfile_nts"
    image: "nts:${VER}"
    privileged: true
    volumes:
     - "/dev/huge_1GB:/hugepages"
     - "/var/lib/appliance/nts:/var/lib/appliance/nts"
     - "/var/run/docker/netns:/var/run/docker/netns"
     - "/var/run:/var/run"
     - "/proc/1/ns:/var/host_ns"
     - "/sys/class/net:/var/host_net_devices"
    environment:
     - NTS_SOCKET0_MEM=${NTS_MEM_MB_S0}
     - NTS_SOCKET1_MEM=${NTS_MEM_MB_S1}
    network_mode: host

  syslog-ng:
    image:  balabit/syslog-ng:3.19.1
    volumes:
      - "/var/lib/appliance/configs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro"
      - "/var/lib/appliance/certs:/etc/syslog-ng/certs:ro"
      - "/var/log/appliance:/var/log"

    command: "--no-caps"
    extra_hosts:
      - "syslog.community.controller.mec:${REMOTE_SYSLOG_IP}"
    ports:
      - "192.168.122.1:514:514/udp"
    network_mode: bridge
